// Fresh internet-sourced service-only visual library.
// 0: listing + hero; 1: video poster; 2: operational/GIF preview;
// 3-5: gallery; 6: related-service card. Each source file is unique within its service.
export const UNIQUE_SERVICE_MEDIA: Record<string, string[]> = {
  "vehicle-tracking": [
    "/media/services-fresh/vehicle-tracking-1.webp",
    "/media/services-fresh/vehicle-tracking-2.webp",
    "/media/services-fresh/vehicle-tracking-3.jpg",
    "/media/services-fresh/vehicle-tracking-4.jpg",
    "/media/services-fresh/vehicle-tracking-5.jpg",
    "/media/services-fresh/vehicle-tracking-6.jpg",
    "/media/services-fresh/vehicle-tracking-7.webp",
  ],
  "fleet-management": [
    "/media/services-fresh/fleet-management-1.webp",
    "/media/services-fresh/fleet-management-2.webp",
    "/media/services-fresh/fleet-management-3.webp",
    "/media/services-fresh/fleet-management-4.jpg",
    "/media/services-fresh/fleet-management-5.png",
    "/media/services-fresh/fleet-management-6.png",
    "/media/services-fresh/fleet-management-7.jpg",
  ],
  "dashcam-solutions": [
    "/media/services-fresh/dashcam-solutions-1.jpg",
    "/media/services-fresh/dashcam-solutions-2.jpg",
    "/media/services-fresh/dashcam-solutions-3.jpg",
    "/media/services-fresh/dashcam-solutions-4.webp",
    "/media/services-fresh/dashcam-solutions-5.png",
    "/media/services-fresh/dashcam-solutions-6.png",
    "/media/services-fresh/dashcam-solutions-7.png",
  ],
  "personalized-tracking": [
    "/media/services-fresh/personalized-tracking-1.png",
    "/media/services-fresh/personalized-tracking-2.jpg",
    "/media/services-fresh/personalized-tracking-3.jpg",
    "/media/services-fresh/personalized-tracking-4.jpg",
    "/media/services-fresh/personalized-tracking-5.jpg",
    "/media/services-fresh/personalized-tracking-6.webp",
    "/media/services-fresh/personalized-tracking-7.jpg",
  ],
  "custom-software": [
    "/media/services-fresh/custom-software-1.webp",
    "/media/services-fresh/custom-software-2.webp",
    "/media/services-fresh/custom-software-3.jpg",
    "/media/services-fresh/custom-software-4.jpg",
    "/media/services-fresh/custom-software-5.jpg",
    "/media/services-fresh/custom-software-6.webp",
    "/media/services-fresh/custom-software-7.png",
  ],
  "government-fleet": [
    "/media/services-fresh/government-fleet-1.png",
    "/media/services-fresh/government-fleet-2.jpg",
    "/media/services-fresh/government-fleet-3.jpg",
    "/media/services-fresh/government-fleet-4.jpg",
    "/media/services-fresh/government-fleet-5.jpg",
    "/media/services-fresh/government-fleet-6.png",
    "/media/services-fresh/government-fleet-7.webp",
  ],
  "ev-bms": [
    "/media/services-fresh/ev-bms-1.jpg",
    "/media/services-fresh/ev-bms-2.webp",
    "/media/services-fresh/ev-bms-3.webp",
    "/media/services-fresh/ev-bms-4.jpg",
    "/media/services-fresh/ev-bms-5.webp",
    "/media/services-fresh/ev-bms-6.jpg",
    "/media/services-fresh/ev-bms-7.png",
  ],
  "reflective-tape": [
    "/media/services-fresh/reflective-tape-1.jpg",
    "/media/services-fresh/reflective-tape-2.jpg",
    "/media/services-fresh/reflective-tape-3.jpg",
    "/media/services-fresh/reflective-tape-4.jpg",
    "/media/services-fresh/reflective-tape-5.jpg",
    "/media/services-fresh/reflective-tape-6.jpg",
    "/media/services-fresh/reflective-tape-7.jpg",
  ],
  "technical-support": [
    "/media/services-fresh/technical-support-1.webp",
    "/media/services-fresh/technical-support-2.jpg",
    "/media/services-fresh/technical-support-3.jpg",
    "/media/services-fresh/technical-support-4.jpg",
    "/media/services-fresh/technical-support-5.jpg",
    "/media/services-fresh/technical-support-6.jpg",
    "/media/services-fresh/technical-support-7.jpg",
  ],
  "installation-deployment": [
    "/media/services-fresh/installation-deployment-1.png",
    "/media/services-fresh/installation-deployment-2.png",
    "/media/services-fresh/installation-deployment-3.jpeg",
    "/media/services-fresh/installation-deployment-4.jpg",
    "/media/services-fresh/installation-deployment-5.webp",
    "/media/services-fresh/installation-deployment-6.png",
    "/media/services-fresh/installation-deployment-7.jpg",
  ],
  "after-sales-service": [
    "/media/services-fresh/after-sales-service-1.png",
    "/media/services-fresh/after-sales-service-2.jpg",
    "/media/services-fresh/after-sales-service-3.jpg",
    "/media/services-fresh/after-sales-service-4.png",
    "/media/services-fresh/after-sales-service-5.webp",
    "/media/services-fresh/after-sales-service-6.png",
    "/media/services-fresh/after-sales-service-7.jpg",
  ],
};

export const getUniqueServiceMedia = (id: string, fallback: string[]) =>
  UNIQUE_SERVICE_MEDIA[id] ?? fallback;
